# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\contents\interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(468, 141)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gpsLine = QtWidgets.QLineEdit(self.centralwidget)
        self.gpsLine.setGeometry(QtCore.QRect(10, 10, 361, 20))
        self.gpsLine.setObjectName("gpsLine")
        self.gpsButton = QtWidgets.QPushButton(self.centralwidget)
        self.gpsButton.setGeometry(QtCore.QRect(380, 10, 75, 23))
        self.gpsButton.setObjectName("gpsButton")
        self.programLine = QtWidgets.QLineEdit(self.centralwidget)
        self.programLine.setGeometry(QtCore.QRect(10, 40, 361, 20))
        self.programLine.setObjectName("programLine")
        self.programsButton = QtWidgets.QPushButton(self.centralwidget)
        self.programsButton.setGeometry(QtCore.QRect(380, 40, 75, 23))
        self.programsButton.setObjectName("programsButton")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(380, 70, 75, 41))
        self.startButton.setObjectName("startButton")
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(mainWindow)
        self.statusBar.setObjectName("statusBar")
        mainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Time Space Diagram Maker"))
        self.gpsButton.setText(_translate("mainWindow", "GPS Data"))
        self.programsButton.setText(_translate("mainWindow", "Programs"))
        self.startButton.setText(_translate("mainWindow", "Start"))